# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GreetingService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15GreetingService.proto\x12\x0cname_package\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x07Greeter\x12\x38\n\x08sayHello\x12\x15.name_package.Request\x1a\x13.name_package.Reply\"\x00\x42=\n\x1dio.grpc.examples.name_packageB\x14GreetingServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'GreetingService_pb2'
  # @@protoc_insertion_point(class_scope:name_package.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'GreetingService_pb2'
  # @@protoc_insertion_point(class_scope:name_package.Reply)
  })
_sym_db.RegisterMessage(Reply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035io.grpc.examples.name_packageB\024GreetingServiceProtoP\001\242\002\003HLW'
  _REQUEST._serialized_start=39
  _REQUEST._serialized_end=62
  _REPLY._serialized_start=64
  _REPLY._serialized_end=88
  _GREETER._serialized_start=90
  _GREETER._serialized_end=157
# @@protoc_insertion_point(module_scope)
